name: Node Setup

on: push

jobs:
  node-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print Node Version
        run: node -v
